version: "1.0"

services:
    museum_api:
        container_name: museum_api
        build:
            context: .
        command: bash -c 'gunicorn --config ./gunicorn.conf.py --workers 4 --timeout 120'
        ports:
          - ${PORT}:8080
        restart: on-failure
